---
title: 'Tree tests'
author: 'DIVERS'
date: '`r format(Sys.time(), "%B %d, %Y")`'
output:
  html_document:
    toc: yes
    toc_depth: 3
  classoption: a4paper
  md_document:
    variant: markdown_github
  pdf_document:
    fig_caption: yes
    toc: yes
    toc_depth: 3
  word_document: default
---

#Background



```{r libraries, message=FALSE}
library(ape)
```

```{r read.data, message=FALSE}

dat<-read.csv(file="data extracted from PROTEUS on 22_11_2021.csv", header=T)

sp<-dat$species
sp<-gsub(" ", "_", sp)

head(sp)

mtree<-read.tree(file="GBMB.tre")

to.keep<-intersect(sp,mtree$tip.label)

tree.genus<-gsub("_.*", "", mtree$tip.label)
#mtree$tip.label[which(tree.genus=="Oxalis")]

to.graft<-setdiff(sp,mtree$tip.label)
to.graft.genus<-gsub("_.*", "", to.graft)

#Pick a random species per genus from the tree that has not been picked yet:
left.sp<-setdiff(mtree$tip.label,sp)

add.sp<-rep(NA, length(to.graft))

#Find species in the same genus as the target species to add (to.graft)
for(i in 1:length(to.graft)){
  add.sp[i]<-left.sp[which(gsub("_.*","",left.sp)==to.graft.genus[i])][1]
}

cbind(add.sp, to.graft) #Species in tree / species in trait list

to.add<-add.sp[!is.na(add.sp)]

ptree<-keep.tip(mtree, c(to.keep, to.add))
#Replace 
na.omit(data.frame(add.sp, to.graft))

write.tree(ptree, file="tree_herve.tre")

```
