---
title: 'DiVERS'
author: '[Mario Vallejo-Marin](http://www.plant-evolution.org)'
date: '`r format(Sys.time(), "%B %d, %Y")`'
output:
  html_document:
    toc: yes
    toc_depth: 3
  classoption: a4paper
  md_document:
    variant: markdown_github
  pdf_document:
    fig_caption: yes
    toc: yes
    toc_depth: 3
  word_document: default
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Libraries

```{r libraries}
library(ape)
library(phytools)
library(Hmisc)
library(adephylo)
library(phylobase)
```


#Set Working Directory

Set up the local working directory containing the data set and tree files.

The tree and data set are in the Githuib repository:

https://github.com/mvallejo6/divers-tree

```{r set.wd}
workdir<-"/Users/mario/Downloads/"

#This is the data set generated in Andrew's script (github repository)
df_orig<-readRDS(file=paste(workdir,"df_filt_trans.rds", sep=""))

#This is the tree with phylogenetic information (github)
tree<-read.tree(file=paste(workdir,"GBMB.txt", sep=""))

```

# Phylogenetic analysis (pPCA)


```{r p.pca}
#Extract the species names from the phenotype dataset and replace " " with "_":
spp<-row.names(df_orig)
row.names(df_orig)<-gsub(" ", "_", spp)

#Check the number of taxas overlapping in the tree and dataset:
sum(row.names(df_orig) %in% tree$tip.label) #Species in data set also in the tree
sum(tree$tip.label %in% row.names(df_orig) ) #Species in the tree also in the dataset

#Select only taxa for which there is data
tokeep<-tree$tip.label [tree$tip.label %in% row.names(df_orig)] 

#Prune the tree:
stree<-keep.tip(tree, tokeep)

#Create new data set with only the species that also appear in the tree:
#Keep only numeric columns (first six columns)
dat<-df_orig[row.names(df_orig) %in% tree$tip.label, 1:6] 

#Create a dataframe that includes both trait data and the phylogenetic tree:
stree.4d<-phylo4d(stree, dat)

#Calculate the Phylogenetic PCA:
flow.ppca<- ppca(stree.4d,scale=FALSE,scannf=FALSE,nfposi=1,nfnega=1, method="Abouheif")

#Percent of variance explained?
flow.ppca$eig/sum(flow.ppca$eig)*100

abs(flow.ppca$eig)/sum(abs(flow.ppca$eig))*100

plot(flow.ppca)


```

## Standard PCA


```{r pca}

#This method uses imputation to fill the NA entries

#Now run the standard PCA:

#First impute the data that is missing:
#require(Hmisc) #To inpute missing values

#Create new data frame to fill in with impouted data:
imp.dat<-dat

#Make loop for inputing data for each of the columns:

for(i in 1:dim(imp.dat)[2]){
imp.dat[,i] <- impute(imp.dat[,i], fun=mean)
}

#which(row.names(imp.dat)=="Thalictrum_minus")

#Now run the PCA:
pc1<-princomp(imp.dat)

#Plot the PCA results using ggfortify:

require(ggfortify)

autoplot(pc1, data = imp.dat, loadings = TRUE, loadings.label=T)


```

## Phylogeny-corrected PCA (phytools)

Revell (2009) Evolution

http://www.phytools.org/static.help/phyl.pca.html


```{r phylo.pca}
require(phytools)
phy.pca<-phyl.pca(tree=stree, Y = imp.dat)

phy.pca<-as.princomp(phy.pca)
#biplot(phy.pca)
autoplot(phy.pca, data = imp.dat, loadings = TRUE, loadings.label=T)



```


